sudo: required
services:
    - docker
before_install:
    - docker build -t docker-react-pr -f Dockerfile.dev .
script:
    - docker run docker-react-pr npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-ap-northeast-1-717573596828
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY